DROP DATABASE IF EXISTS competition;
CREATE DATABASE competition;
USE competition;

CREATE TABLE user (
id INT (11) NOT NULL AUTO_INCREMENT,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(50) NOT NULL,
login VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY (login)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE contestant (
id INT (11) NOT NULL, 
companyName VARCHAR(50),
PRIMARY KEY (id),
FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE expert (
id INT (11) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE session (
id INT (11) NOT NULL AUTO_INCREMENT,
token VARCHAR(50),
userid INT (11) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (userid) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE application (
id INT (11) NOT NULL AUTO_INCREMENT,
title VARCHAR(50) NOT NULL,
description VARCHAR(50) NOT NULL,
requestedAmount INT (11) NOT NULL,
contestantid INT (11) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY title_contestantid (title, contestantid),
FOREIGN KEY (contestantid) REFERENCES contestant (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE direction (
id INT (11) NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
applicationid INT(11),
expertid INT(11),
PRIMARY KEY (id),
FOREIGN KEY (applicationid) REFERENCES application (id) ON DELETE CASCADE,
FOREIGN KEY (expertid) REFERENCES expert (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE rating (
id INT (11) NOT NULL AUTO_INCREMENT,
rating INT(11) NOT NULL,
applicationid INT(11) NOT NULL,
expertid INT(11) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (applicationid) REFERENCES application (id) ON DELETE CASCADE,
FOREIGN KEY (expertid) REFERENCES expert (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;